version: '3.1'

services:
  db:
    image: postgres:15
    user: root
    restart: always
    environment:
      - "POSTGRES_PASSWORD=someOd00passwd"
      - "POSTGRES_DB=odoo"
      - "POSTGRES_USER=odoo"
    volumes:
      - "odoo-db-data:/var/lib/postgresql/data"
    
  odoo16:
    image: odoo:16
    user: root
    depends_on:
      - db
      
    volumes:
      - "odoo-db-data:/var/lib/postgresql/data/pgdata"
      - "odoo-data:/mnt/extra-addons"
      - "odoo-data:/etc:/etc/odoo"

    environment:
      - "HOST=db"
      - "USER=odoo"
      - "PASSWORD=someOd00passwd"

volumes:
  odoo-data:
  odoo-db-data:

volumes:
  db-data:
    driver: local
